### ISSUE TITLE
Address namespace issue

### ISSUE THREAD

**Issue by paltman** [pinax/django-stripe-payments#169]
Having a namespace of `payments` has been an known issue for quite a long time. The only obvious solution is renaming the package from `payments` to something else.

Whatever we call it, I'm inclined to keep the PyPI name `django-stripe-payments` as it's fairly well known now and renaming might cause confusion.

Some straw-man proposals:

* `pinax.payments`
* `pinax.stripe`
* `pinax.stripe_payments`
* `pinax.dsp`
* `pinax.striped`
* `pinax.strp`

I think having a generic `payments` namespace implies it works with more than just Stripe which is bad for more than just namespace collision reasons.  The `stripe` package *might* have collisions with a `pinax.stripe` module, but not sure. I think this is my favorite if that won't be a problem.  My second favorite is `pinax.dsp` as it would tie into the PyPI and original name of `django-stripe-payments`.

I'm open to ideas from the community!

**Comment by jacobwegner** [comment]
I like pinax.stripe or pinax.stripe_payments...agree that "payments" might confuse what the app offers, and the naming convention mirrors other Pinax apps.

We don't have a pinax.evntlg after all ;)

**Comment by paltman** [comment]
I think we'll settle on `pinax.stripe`. Would be great to have @brosner weigh in on this before we make it final, though.

**Comment by paltman** [comment]
I'm also thinking we bite the bullet and rename the PyPI name to `pinax-stripe`. Github will redirect once we rename the repo and we can update the old PyPI listing for DSP with a pointer to the `pinax-stripe`.
