### ISSUE TITLE
Address issue with SubfieldBase on Django 1.9

### ISSUE THREAD

**Issue by paltman** [pinax/django-stripe-payments#183]
This is stemming from latest version of `django-jsonfield` and will apply pretty widely to Pinax projects/apps.

**Comment by JPWKU** [comment]
I read up on this so I thought I'd write here for posterity.
I browsed the django repository and found this 
https://github.com/django/django/blob/aaacaeb0963c406c4fe6f68c6ae51f4a65878250/django/db/models/fields/subclassing.py#L21 ... In fact the sublassing.py module no longer exists.  Here is how it was used in django-jsonfield:
django-jsonfield copied that file over into their repo directly here https://github.com/JPWKU/django-jsonfield/blob/master/jsonfield/subclassing.py and used it here https://github.com/JPWKU/django-jsonfield/blob/master/jsonfield/fields.py#L53

**Comment by paltman** [comment]
I was testing against Django `master` which has already flipped over to `1.10`. The existing [django-jsonfield](https://bitbucket.org/schinckel/django-jsonfield/) used by Pinax works with `1.9`.

However, in the process, I tested [jsonfield](https://github.com/bradjasper/django-jsonfield) against `master` and it worked just fine. We might should re-evaluate the standard Pinax library we use for JSON fields. They seem to have an interchangeable public API.
